# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'EZForm', '~> 1.1.4'
pod 'Typhoon', '~> 2.3.4'
pod 'RHAddressBook', '~> 1.1.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'SocketRocket', '~> 0.3.1-beta2'
pod 'JSONModel', '~> 1.0.1'
pod 'BMPageViewController', '~> 1.0'
pod 'WebSocketRails', '~> 1.1'
pod 'EGODatabase', '~> 2.0'
pod 'Reachability', '~> 3.1'
pod 'TestFairy', '~> 1.3'